#!/bin/sh
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Open pdfs easier
alias za='zathura --fork'

# Trash with tt (to-trash) using trash-cli
alias tt=trash

# Edit file with e
alias e=$EDITOR
# Open file with o (with xdg-open, i.e. default application)
alias o=xdg-open

# Edit bashrc
alias bashrc='$EDITOR ~/.bashrc'
alias vimrc='$EDITOR ~/.config/nvim/init.vim'

# Navigate to parent
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# Color for grep output
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# ls commands
alias ls='ls --color=auto'
alias la='ls -A'
alias ll='ls -lAFh'
alias l.='ls -Alh --ignore="[^.]*"'

# git aliases
alias gc='git commit -am'
alias gs='git status -sb'
alias gk='gitk --all &'
alias gp='git push'

